/* ProfitLands business/location + UI polish layer */
(function(){
  const LOCATIONS=[
    {id:'downtown',name:'Downtown',icon:'🏙️',demand:1.22,rent:1.30,desc:'Huge customer traffic, but expensive to operate.'},
    {id:'suburbs',name:'Suburbs',icon:'🏘️',demand:0.94,rent:0.82,desc:'Steady local demand with lower operating costs.'},
    {id:'tourist',name:'Tourist District',icon:'🌴',demand:1.35,rent:1.42,desc:'Very high demand with very high operating costs.'},
    {id:'university',name:'University District',icon:'🎓',demand:1.14,rent:0.98,desc:'Strong demand from students and young customers.'},
    {id:'waterfront',name:'Waterfront',icon:'🌊',demand:1.18,rent:1.18,desc:'Popular destination with above-average costs.'},
    {id:'tech',name:'Tech District',icon:'💻',demand:1.10,rent:1.08,desc:'Strong demand for modern services and products.'},
    {id:'industrial',name:'Industrial Park',icon:'🏭',demand:0.88,rent:0.68,desc:'Lower customer traffic, but very cheap space.'}
  ];
  const moneyFmt=n=>money(n);
  function normalize(){state.businesses=state.businesses||[];state.businesses.forEach(b=>{if(!Array.isArray(b.locations)||!b.locations.length)b.locations=[{id:'downtown',name:'Downtown',icon:'🏙️',demand:1.22,rent:1.30,basePopularity:b.popularity||55}];b.chainCount=Math.max(0,b.locations.length-1);b.locations.forEach(l=>{if(l.basePopularity==null)l.basePopularity=b.popularity||55})})}
  function hash(n){let x=Math.sin(n*12.9898)*43758.5453;return x-Math.floor(x)}
  function locationDaily(b,l,index){const t=BUSINESS_TYPES.find(x=>x.id===b.type);const levelMult=1+(b.level-1)*.22;const popularity=Math.max(0,Math.min(100,(l.basePopularity||b.popularity||55)+b.marketing*1.5))/100;const variance=.82+hash(state.day*97+index*31+String(l.id).length*17)*.36;const revenue=t.baseRevenue*levelMult*l.demand*(.45+popularity*.8)*(1+b.marketing*.08)*variance;const expense=t.baseExpense*levelMult*l.rent*(1+b.efficiency*.07);return Math.round(revenue-expense)}
  function totalProfit(b){return b.locations.reduce((sum,l,i)=>sum+locationDaily(b,l,i),0)}
  function value(b){const t=BUSINESS_TYPES.find(x=>x.id===b.type);return t.cost*(1+b.level*.15)+b.locations.slice(1).reduce((sum,l,idx)=>sum+t.cost*10*(1+idx*.35)*.55,0)}
  function uniqueOwned(typeId){return state.businesses.some(b=>b.type===typeId)}
  function buyBusinessFixed(typeId){const t=BUSINESS_TYPES.find(x=>x.id===typeId);if(!t)return;if(uniqueOwned(typeId)){toast(`You already own a ${t.name}. Expand its chain instead.`);return}if(!spendAction(t.cost))return;const popularity=50+Math.random()*20;const b={type:typeId,name:`${t.name} #${state.businesses.length+1}`,level:1,popularity,marketing:0,efficiency:0,chainCount:0,locations:[{id:'downtown',name:'Downtown',icon:'🏙️',demand:1.22,rent:1.30,basePopularity:popularity}]};state.businesses.push(b);state.news.push(`You opened ${b.name} in Downtown.`);closeModal('businessModal');toast(`${t.name} opened in Downtown.`);save();render()}
  function renderBusinessShopFixed(){const box=$('businessChoices');if(!box)return;box.innerHTML=BUSINESS_TYPES.map(t=>{const owned=uniqueOwned(t.id);return `<button class="business-choice ${owned?'owned-choice':''}" data-buy-type="${t.id}" ${owned?'disabled':''}><h4>${t.icon} ${t.name}</h4><p>${owned?'Already owned. Expand this company to open another location.':t.desc}</p><div class="choice-bottom"><span>${owned?'OWNED':'START COMPANY'}</span><span>${owned?'CHAIN EXPANSION':moneyFmt(t.cost)}</span></div></button>`}).join('');box.querySelectorAll('[data-buy-type]').forEach(el=>el.onclick=()=>buyBusinessFixed(el.dataset.buyType))}
  function locationPicker(index){const b=state.businesses[index],t=BUSINESS_TYPES.find(x=>x.id===b.type);if(!b)return;const occupied=new Set(b.locations.map(l=>l.id));const number=b.locations.length+1;const cost=Math.round(t.cost*10*(1+(b.locations.length-1)*.35));$('manageContent').innerHTML=`<div class="location-picker"><span class="eyebrow">CHAIN EXPANSION</span><h2>Choose Location #${number}</h2><p class="modal-sub">Your first expansion costs 10× the original ${t.name} price. Pick where your next location should open.</p><div class="location-grid">${LOCATIONS.map(l=>{const used=occupied.has(l.id);const temp={...b,locations:[l]};const profit=used?0:locationDaily(temp,l,0);return `<button class="location-card" data-location="${l.id}" ${used?'disabled':''}><div class="location-icon">${l.icon}</div><div class="location-main"><b>${l.name}</b><small>${l.desc}</small><span>Demand ${Math.round(l.demand*100)}% · Rent ${Math.round(l.rent*100)}%</span></div><strong>${used?'OWNED':(profit>=0?'+':'')+moneyFmt(profit)+'/day'}</strong></button>`}).join('')}</div><div class="location-cost">Expansion cost <b>${moneyFmt(cost)}</b></div><button class="secondary-button" id="backToManage">← Back to company</button></div>`;document.querySelectorAll('[data-location]').forEach(el=>el.onclick=()=>openLocation(index,el.dataset.location));$('backToManage').onclick=()=>openManage(index)}
  function openLocation(index,id){const b=state.businesses[index],t=BUSINESS_TYPES.find(x=>x.id===b.type),l=LOCATIONS.find(x=>x.id===id);if(!b||!l)return;if(b.locations.some(x=>x.id===id)){toast('That location is already part of this chain.');return}const cost=Math.round(t.cost*10*(1+(b.locations.length-1)*.35));if(!spendAction(cost))return;b.locations.push({id:l.id,name:l.name,icon:l.icon,demand:l.demand,rent:l.rent,basePopularity:Math.min(100,(b.popularity||55)+Math.random()*8-4)});b.chainCount=b.locations.length-1;state.news.push(`${b.name} opened Location #${b.locations.length} in ${l.name}.`);toast(`${l.name} location opened.`);save();render();closeModal('manageModal')}
  function renderBusinessesFixed(){if(!state.businesses.length){$('businessList').innerHTML='<div class="empty">No businesses yet. Buy one to start building your empire.</div>';return}$('businessList').innerHTML=state.businesses.map((b,i)=>{const t=BUSINESS_TYPES.find(x=>x.id===b.type),p=totalProfit(b);return `<div class="business-card" data-business="${i}"><div class="business-top"><div><div class="business-name">${t.icon} ${b.name}</div><div class="business-type">${t.name} · Level ${b.level} · ${b.locations.length} location${b.locations.length===1?'':'s'}</div></div><div class="business-profit ${p<0?'danger':''}">${p>=0?'+':''}${moneyFmt(p)}/day</div></div><div class="business-meta"><div class="mini-stat"><small>POPULARITY</small><b>${Math.round(b.popularity)}%</b><div class="popbar"><i style="width:${Math.max(0,Math.min(100,b.popularity))}%"></i></div></div><div class="mini-stat"><small>LOCATIONS</small><b>${b.locations.length}</b></div><div class="mini-stat"><small>UPGRADES</small><b>${b.level-1}</b></div><div class="mini-stat"><small>HEALTH</small><b class="${p<0?'danger':'good'}">${p<0?'LOSS':'PROFIT'}</b></div></div></div>`}).join('');document.querySelectorAll('.business-card').forEach(el=>el.onclick=()=>openManage(Number(el.dataset.business)))}
  function openManageFixed(index){const b=state.businesses[index],t=BUSINESS_TYPES.find(x=>x.id===b.type);if(!b)return;const profit=totalProfit(b),upgradeCost=Math.round(t.cost*(1+b.level*.75)),chainCost=Math.round(t.cost*10*(1+(b.locations.length-1)*.35)),marketingCost=Math.round(t.cost*.65*(b.marketing+1)),efficiencyCost=Math.round(t.cost*.7*(b.efficiency+1));$('manageContent').innerHTML=`<div class="manage-head"><div><span class="eyebrow">COMPANY MANAGEMENT</span><h2>${t.icon} ${b.name}</h2><p class="modal-sub">${t.desc}</p></div><div class="business-profit ${profit<0?'danger':''}">${profit>=0?'+':''}${moneyFmt(profit)}/day</div></div><div class="manage-stats"><div class="mini-stat"><small>LEVEL</small><b>${b.level}</b></div><div class="mini-stat"><small>POPULARITY</small><b>${Math.round(b.popularity)}%</b></div><div class="mini-stat"><small>LOCATIONS</small><b>${b.locations.length}</b></div><div class="mini-stat"><small>STATUS</small><b class="${profit<0?'danger':'good'}">${profit<0?'LOSING':'PROFITABLE'}</b></div></div><div class="location-summary">${b.locations.map((l,i)=>`<div><span>${l.icon}</span><b>Location ${i+1}</b><small>${l.name}</small><strong>${locationDaily(b,l,i)>=0?'+':''}${moneyFmt(locationDaily(b,l,i))}/day</strong></div>`).join('')}</div><div class="manage-actions"><button class="upgrade-button" data-manage="upgrade"><b>⬆ Upgrade Business</b><small>Level ${b.level+1} · ${moneyFmt(upgradeCost)}</small></button><button class="upgrade-button" data-manage="marketing"><b>📢 Marketing</b><small>+8 popularity · ${moneyFmt(marketingCost)}</small></button><button class="upgrade-button" data-manage="efficiency"><b>⚙ Improve Efficiency</b><small>Lower daily expenses · ${moneyFmt(efficiencyCost)}</small></button><button class="upgrade-button" data-manage="sell"><b>💰 Sell Business</b><small>Recover part of its current value</small></button></div><div class="chain-box"><b>🏢 Chain Expansion</b><p class="modal-sub">Open another ${t.name} location. You choose the location, and the first expansion costs 10× the original business price.</p><button class="chain-button" data-manage="chain" ${state.cash<chainCost?'disabled':''}>Choose Location #${b.locations.length+1} · ${moneyFmt(chainCost)}</button></div>`;$('manageModal').classList.remove('hidden');document.querySelectorAll('[data-manage]').forEach(el=>el.onclick=()=>manageActionFixed(index,el.dataset.manage))}
  function manageActionFixed(index,what){const b=state.businesses[index],t=b&&BUSINESS_TYPES.find(x=>x.id===b.type);if(!b||!t)return;if(what==='chain'){locationPicker(index);return}if(what==='upgrade'){const c=Math.round(t.cost*(1+b.level*.75));if(!spendAction(c))return;b.level++;state.news.push(`${b.name} reached Level ${b.level}.`);toast('Business upgraded.')}else if(what==='marketing'){const c=Math.round(t.cost*.65*(b.marketing+1));if(!spendAction(c))return;b.marketing++;b.popularity=Math.min(100,b.popularity+8);b.locations.forEach(l=>l.basePopularity=Math.min(100,l.basePopularity+8));toast('Marketing boosted popularity.')}else if(what==='efficiency'){const c=Math.round(t.cost*.7*(b.efficiency+1));if(!spendAction(c))return;b.efficiency++;toast('Efficiency improved.')}else if(what==='sell'){const refund=Math.round(value(b)*.7);state.cash+=refund;state.businesses.splice(index,1);state.news.push(`You sold ${b.name} for ${moneyFmt(refund)}.`);toast('Business sold.');closeModal('manageModal')}save();render();if(what!=='sell')openManageFixed(index)}
  function renderTradeModal(id){const s=STOCKS.find(x=>x.id===id);if(!s)return;const h=state.stocks[id]||{shares:0};let quantity=1;const modal=$('manageModal');const content=$('manageContent');const change=s._change||0;const update=()=>{const total=s.price*quantity;const canBuy=state.actions>0&&state.cash>=total;const canSell=state.actions>0&&h.shares>=quantity;content.querySelector('#tradeQty').value=quantity;content.querySelector('#tradeTotal').textContent=moneyFmt(total);content.querySelector('#tradeBuy').disabled=!canBuy;content.querySelector('#tradeSell').disabled=!canSell;content.querySelector('#tradeBuyNote').textContent=state.actions<=0?'No actions left.':state.cash<total?'Not enough cash.':'Uses 1 action';content.querySelector('#tradeSellNote').textContent=state.actions<=0?'No actions left.':h.shares<quantity?'Not enough shares.':'Uses 1 action'};content.innerHTML=`<div class="trade-modal"><span class="eyebrow">STOCK MARKET</span><div class="trade-head"><div><h2>${s.name}</h2><p class="modal-sub">${s.ticker} · ${s.sector} · ${s.risk} risk</p></div><div class="trade-price"><strong>${moneyFmt(s.price)}</strong><span class="${change>=0?'good':'danger'}">${change>=0?'+':''}${change.toFixed(1)}%</span></div></div><div class="trade-stats"><div><small>YOUR SHARES</small><b>${h.shares}</b></div><div><small>HOLDING VALUE</small><b>${moneyFmt(h.shares*s.price)}</b></div><div><small>CASH</small><b>${moneyFmt(state.cash)}</b></div></div><div class="trade-quantity"><label for="tradeQty">Quantity</label><div class="quantity-control"><button type="button" id="tradeMinus">−</button><input id="tradeQty" type="number" min="1" max="999999" value="1" inputmode="numeric"><button type="button" id="tradePlus">+</button></div><div class="trade-total">Order total <strong id="tradeTotal">${moneyFmt(s.price)}</strong></div></div><div class="trade-actions"><button type="button" class="trade-button buy" id="tradeBuy"><b>Buy Shares</b><small id="tradeBuyNote">Uses 1 action</small></button><button type="button" class="trade-button sell" id="tradeSell"><b>Sell Shares</b><small id="tradeSellNote">Uses 1 action</small></button></div><button type="button" class="secondary-button" id="tradeCancel">Cancel</button></div>`;modal.classList.remove('hidden');const clamp=()=>{quantity=Math.max(1,Math.min(999999,Math.floor(Number(content.querySelector('#tradeQty').value)||1)));update()};content.querySelector('#tradeQty').addEventListener('input',clamp);content.querySelector('#tradeMinus').onclick=()=>{quantity=Math.max(1,quantity-1);update()};content.querySelector('#tradePlus').onclick=()=>{quantity=Math.min(999999,quantity+1);update()};content.querySelector('#tradeCancel').onclick=()=>closeModal('manageModal');content.querySelector('#tradeBuy').onclick=()=>executeTrade(id,'buy',quantity);content.querySelector('#tradeSell').onclick=()=>executeTrade(id,'sell',quantity);update()}
  function executeTrade(id,type,quantity){const s=STOCKS.find(x=>x.id===id);const h=state.stocks[id]||{shares:0};const total=s.price*quantity;if(state.actions<=0)return toast('No actions left.');if(type==='buy'){if(state.cash<total)return toast('Not enough cash.');state.cash-=total;h.shares+=quantity;state.stocks[id]=h;state.actions--;state.news.push(`You bought ${quantity} share${quantity===1?'':'s'} of ${s.ticker}.`);toast(`Bought ${quantity} ${s.ticker} share${quantity===1?'':'s'}.`)}else{if(h.shares<quantity)return toast('You do not own enough shares.');state.cash+=total;h.shares-=quantity;state.stocks[id]=h;state.actions--;state.news.push(`You sold ${quantity} share${quantity===1?'':'s'} of ${s.ticker}.`);toast(`Sold ${quantity} ${s.ticker} share${quantity===1?'':'s'}.`)}save();render();if($('manageModal'))$('manageModal').classList.add('hidden')}
  window.trade=renderTradeModal;
  window.businessDailyProfit=totalProfit;window.businessValue=value;window.totalBusinessProfit=()=>state.businesses.reduce((s,b)=>s+totalProfit(b),0);window.netWorth=()=>state.cash+STOCKS.reduce((s,x)=>s+x.price*(state.stocks[x.id]?.shares||0),0)+state.businesses.reduce((s,b)=>s+value(b),0)+state.property*750;window.buyBusiness=buyBusinessFixed;window.openManage=openManageFixed;window.manageAction=manageActionFixed;window.renderBusinesses=renderBusinessesFixed;
  normalize();setTimeout(()=>{render();renderBusinessShopFixed()},0);document.addEventListener('click',e=>{if(e.target.closest('#openBusinessShop'))setTimeout(renderBusinessShopFixed,0)})
})();