/* ProfitLands player identity layer */
(function(){
  const PLAYER_KEY='profitlands-player-name';
  let approvedStart=false;
  function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function cleanName(v){return v.trim().replace(/\s+/g,' ')}
  const blockedParts=['fuck','shit','bitch','asshole','bastard','dick','piss','cunt','nigger','nigga','faggot','fag','retard'];
  function invalidName(name){const normalized=name.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');if(normalized.length<2||normalized.length>24)return'Name must be 2–24 characters.';if(!/^[\p{L}\p{N} ._'’-]+$/u.test(name))return'Please use letters, numbers, spaces, or simple punctuation.';if(blockedParts.some(w=>normalized.includes(w)))return'That name is not allowed. Please try another name.';return''}
  function ensureModal(){if(document.getElementById('playerNameModal'))return;const modal=document.createElement('div');modal.id='playerNameModal';modal.className='modal hidden';modal.innerHTML='<div class="modal-card player-name-card"><span class="eyebrow">PLAYER PROFILE</span><h2>Name your empire</h2><p class="modal-sub">Choose your player name. Your company name can be changed from Account Settings.</p><label class="player-name-label" for="playerNameInput">YOUR NAME</label><input id="playerNameInput" class="player-name-input" maxlength="24" autocomplete="nickname" placeholder="Enter your name"><div id="playerNameError" class="player-name-error"></div><button id="playerNameContinue" class="primary-button">Continue <span>→</span></button></div>';document.body.appendChild(modal);const input=modal.querySelector('#playerNameInput'),error=modal.querySelector('#playerNameError');modal.querySelector('#playerNameContinue').onclick=()=>{const name=cleanName(input.value),problem=invalidName(name);if(problem){error.textContent=problem;input.focus();return}state.playerName=name;localStorage.setItem(PLAYER_KEY,name);save();modal.classList.add('hidden');approvedStart=true;document.getElementById('startGame')?.click()};input.addEventListener('keydown',e=>{if(e.key==='Enter')modal.querySelector('#playerNameContinue').click()})}
  function askForName(){ensureModal();const modal=document.getElementById('playerNameModal'),input=document.getElementById('playerNameInput'),error=document.getElementById('playerNameError');error.textContent='';input.value=state.playerName||localStorage.getItem(PLAYER_KEY)||'';modal.classList.remove('hidden');setTimeout(()=>input.focus(),30)}
  document.addEventListener('click',e=>{if(e.target.closest('#startGame')&&!approvedStart){e.preventDefault();e.stopImmediatePropagation();askForName()}},true);
  const savedName=localStorage.getItem(PLAYER_KEY);if(savedName&&!state.playerName)state.playerName=savedName;if(!state.playerName)state.playerName='';if(!state.companyName)state.companyName='';
})();