/* ProfitLands persistent HUD support. World news is generated by economy-system.js. */
(function(){
  const install=()=>{
    const head=document.querySelector('.game-head');
    const stats=document.querySelector('.stats-grid');
    if(head)head.classList.add('persistent-hud-head');
    if(stats)stats.classList.add('persistent-hud-stats');
  };
  install();
  setInterval(install,1000);
})();